const PDFDocument = require('pdfkit');

module.exports = function registerPhase2(app,{auth,loadData,saveData,publicUser}){
  const getUser=(req)=>loadData().users.find(u=>u.id===req.user.id);
  const clean=(v,max=120)=>String(v??'').trim().slice(0,max);

  app.get('/api/analytics',auth,(req,res)=>{
    const data=loadData(), invoices=data.invoices.filter(x=>x.userId===req.user.id), expenses=data.expenses.filter(x=>x.userId===req.user.id);
    const byMonth={};
    for(let i=5;i>=0;i--){const d=new Date();d.setMonth(d.getMonth()-i);const key=d.toISOString().slice(0,7);byMonth[key]={month:d.toLocaleDateString('en-NG',{month:'short'}),revenue:0,expenses:0};}
    invoices.forEach(x=>{const k=String(x.createdAt).slice(0,7);if(byMonth[k]&&x.status==='paid')byMonth[k].revenue+=Number(x.total||0);});
    expenses.forEach(x=>{const k=String(x.createdAt).slice(0,7);if(byMonth[k])byMonth[k].expenses+=Number(x.amount||0);});
    const customers={};invoices.forEach(x=>{const k=x.customerEmail||x.customerName;customers[k]=(customers[k]||0)+Number(x.total||0);});
    res.json({months:Object.values(byMonth),topCustomers:Object.entries(customers).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,total])=>({name,total})),counts:{invoices:invoices.length,paid:invoices.filter(x=>x.status==='paid').length,unpaid:invoices.filter(x=>x.status==='unpaid').length,overdue:invoices.filter(x=>x.status==='overdue').length}});
  });

  app.get('/api/settings',auth,(req,res)=>{const u=getUser(req);res.json({name:u.name,email:u.email,businessName:u.businessName,phone:u.phone||'',address:u.address||'',currency:u.currency||'NGN',plan:u.plan});});
  app.patch('/api/settings',auth,(req,res)=>{const data=loadData(),u=data.users.find(x=>x.id===req.user.id);if(!u)return res.status(404).json({message:'User not found.'});u.name=clean(req.body.name,80)||u.name;u.businessName=clean(req.body.businessName,100)||u.businessName;u.phone=clean(req.body.phone,30);u.address=clean(req.body.address,180);u.currency=['NGN','USD','GBP'].includes(req.body.currency)?req.body.currency:'NGN';saveData(data);res.json(publicUser(u));});

  function findInvoice(req){return loadData().invoices.find(x=>x.id===req.params.id&&x.userId===req.user.id);}
  app.get('/api/invoices/:id',auth,(req,res)=>{const x=findInvoice(req);if(!x)return res.status(404).json({message:'Invoice not found.'});res.json(x);});

  app.get('/api/invoices/:id/pdf',auth,(req,res)=>{
    const invoice=findInvoice(req),user=getUser(req);if(!invoice)return res.status(404).json({message:'Invoice not found.'});
    const doc=new PDFDocument({size:'A4',margin:50});res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename="${invoice.number}.pdf"`);doc.pipe(res);
    const money=n=>`NGN ${Number(n||0).toLocaleString('en-NG',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
    doc.fontSize(28).font('Helvetica-Bold').text('billora');doc.fontSize(10).font('Helvetica').fillColor('#666').text('BUSINESS INVOICE',50,85);doc.fillColor('#111');
    doc.fontSize(18).font('Helvetica-Bold').text(invoice.number,400,55,{align:'right'});doc.fontSize(10).font('Helvetica').text(`Issued: ${new Date(invoice.createdAt).toLocaleDateString('en-NG')}`,400,80,{align:'right'});if(invoice.dueDate)doc.text(`Due: ${invoice.dueDate}`,400,95,{align:'right'});
    doc.moveTo(50,125).lineTo(545,125).stroke('#ddd');doc.fontSize(10).font('Helvetica-Bold').text('FROM',50,145);doc.font('Helvetica').text(user.businessName||'Billora business',50,160).text(user.name||'',50,175).text(user.address||'',50,190);doc.font('Helvetica-Bold').text('BILL TO',330,145);doc.font('Helvetica').text(invoice.customerName,330,160).text(invoice.customerEmail||'',330,175);
    let y=235;doc.rect(50,y,495,28).fill('#111');doc.fillColor('#fff').fontSize(9).font('Helvetica-Bold').text('ITEM',62,y+9).text('QTY',370,y+9).text('PRICE',420,y+9).text('TOTAL',490,y+9);y+=28;doc.fillColor('#111').font('Helvetica');
    invoice.items.forEach(item=>{doc.fontSize(10).text(item.description,62,y+10,{width:280}).text(String(item.quantity),370,y+10).text(money(item.price),420,y+10).text(money(item.quantity*item.price),490,y+10);y+=30;doc.moveTo(50,y).lineTo(545,y).stroke('#eee');});
    y+=25;doc.font('Helvetica-Bold').fontSize(11).text('TOTAL',400,y).text(money(invoice.total),490,y);if(invoice.notes){y+=45;doc.font('Helvetica-Bold').text('Notes',50,y);doc.font('Helvetica').text(invoice.notes,50,y+18,{width:495});}doc.fontSize(9).fillColor('#777').text('Generated by Billora — business, beautifully organized.',50,770,{align:'center'});doc.end();
  });

  app.get('/api/invoices/:id/receipt',auth,(req,res)=>{
    const invoice=findInvoice(req),user=getUser(req);if(!invoice)return res.status(404).json({message:'Invoice not found.'});
    const doc=new PDFDocument({size:[226,500],margin:18});res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename="${invoice.number}-receipt.pdf"`);doc.pipe(res);const money=n=>`NGN ${Number(n||0).toLocaleString('en-NG')}`;
    doc.fontSize(18).font('Helvetica-Bold').text('billora',{align:'center'});doc.fontSize(9).font('Helvetica').text(user.businessName||'Business',{align:'center'});doc.moveDown();doc.fontSize(11).font('Helvetica-Bold').text('PAYMENT RECEIPT',{align:'center'});doc.moveDown();doc.fontSize(9).font('Helvetica').text(invoice.number).text(`Date: ${new Date().toLocaleDateString('en-NG')}`).text(`Customer: ${invoice.customerName}`);doc.moveDown();invoice.items.forEach(i=>doc.text(`${i.description} x${i.quantity}`).text(`  ${money(i.quantity*i.price)}`,{align:'right'}));doc.moveDown();doc.font('Helvetica-Bold').fontSize(13).text(`TOTAL  ${money(invoice.total)}`,{align:'center'});doc.moveDown();doc.fontSize(9).font('Helvetica').text(invoice.status==='paid'?'PAID':'PAYMENT PENDING',{align:'center'});doc.moveDown();doc.text('Thank you for your business.',{align:'center'});doc.end();
  });

  app.post('/api/invoices/:id/reminder',auth,(req,res)=>{const x=findInvoice(req);if(!x)return res.status(404).json({message:'Invoice not found.'});const text=`Hello ${x.customerName}, this is a friendly reminder from Billora regarding invoice ${x.number} for NGN ${Number(x.total).toLocaleString('en-NG')}. Thank you.`;res.json({message:'Reminder ready',text,whatsapp:x.customerPhone?`https://wa.me/${String(x.customerPhone).replace(/\D/g,'')}?text=${encodeURIComponent(text)}`:null});});
};
