services:
  - type: web
    name: billora
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: FLW_SECRET_KEY
        sync: false
      - key: FLW_PUBLIC_KEY
        sync: false
      - key: FLW_SECRET_HASH
        sync: false
      - key: BILLORA_PRO_AMOUNT
        value: "4500"
      - key: APP_URL
        sync: false
