const express = require('express');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const crypto = require('crypto');
const PDFDocument = require('pdfkit');
const path = require('path');
const db = require('./db');

const app = express();

const PORT = process.env.PORT || 3000;
const APP_URL = process.env.APP_URL || `http://localhost:${PORT}`;
const JWT_SECRET = process.env.JWT_SECRET || 'change-me-in-production';
const PRO_AMOUNT = Number(process.env.BILLORA_PRO_AMOUNT || 4500);

/* =========================================================
   MIDDLEWARE
========================================================= */

app.use(
  express.json({
    limit: '1mb',
    verify: (req, res, buf) => {
      req.rawBody = buf.toString();
    }
  })
);

app.use(express.static('public'));

/* =========================================================
   HELPERS
========================================================= */

const id = (prefix) =>
  `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;

const pub = (u) => ({
  id: u.id,
  name: u.name,
  email: u.email,
  businessName: u.businessName,
  plan: u.plan,
  phone: u.phone || '',
  address: u.address || '',
  currency: u.currency || 'NGN',
  createdAt: u.createdAt
});

const token = (u) =>
  jwt.sign(
    {
      id: u.id,
      email: u.email
    },
    JWT_SECRET,
    {
      expiresIn: '7d'
    }
  );

function auth(req, res, next) {
  const header = req.headers.authorization || '';
  const t = header.startsWith('Bearer ')
    ? header.slice(7)
    : null;

  if (!t) {
    return res.status(401).json({
      message: 'Authentication required.'
    });
  }

  try {
    req.user = jwt.verify(t, JWT_SECRET);
    next();
  } catch (err) {
    return res.status(401).json({
      message: 'Session expired. Please log in again.'
    });
  }
}

/* =========================================================
   PDF GENERATION
========================================================= */

function pdf(inv, u, receipt = false) {
  return new Promise((resolve, reject) => {
    const d = new PDFDocument({
      margin: 48
    });

    const chunks = [];

    d.on('data', (chunk) => chunks.push(chunk));

    d.on('end', () => {
      resolve(Buffer.concat(chunks));
    });

    d.on('error', reject);

    d.fontSize(24)
      .font('Helvetica-Bold')
      .text(u.businessName || 'Billora');

    d.fontSize(10)
      .font('Helvetica')
      .text(u.address || '');

    if (u.phone) {
      d.text(u.phone);
    }

    d.moveDown(2)
      .fontSize(22)
      .font('Helvetica-Bold')
      .text(receipt ? 'PAYMENT RECEIPT' : 'INVOICE');

    d.fontSize(10)
      .font('Helvetica')
      .text(
        `${inv.number} • ${new Date(inv.createdAt).toLocaleDateString()}`
      );

    d.moveDown()
      .fontSize(12)
      .font('Helvetica-Bold')
      .text('Bill to');

    d.font('Helvetica').text(inv.customerName);

    if (inv.customerEmail) {
      d.text(inv.customerEmail);
    }

    d.moveDown()
      .font('Helvetica-Bold')
      .text('Description                 Qty       Price        Total');

    d.moveDown(0.5);

    inv.items.forEach((item) => {
      d.font('Helvetica').text(
        `${String(item.description)
          .slice(0, 28)
          .padEnd(28)} ${String(item.quantity).padStart(3)}   ${Number(
          item.price
        ).toLocaleString()}   ${(Number(item.quantity) * Number(item.price)).toLocaleString()}`
      );
    });

    d.moveDown()
      .font('Helvetica-Bold')
      .text(
        `Subtotal: ${Number(inv.subtotal).toLocaleString()} ${u.currency}`
      );

    if (Number(inv.vatRate) > 0) {
      d.text(
        `VAT (${inv.vatRate}%): ${(
          Number(inv.total) - Number(inv.subtotal)
        ).toLocaleString()} ${u.currency}`
      );
    }

    d.fontSize(15).text(
      `TOTAL: ${Number(inv.total).toLocaleString()} ${u.currency}`
    );

    d.fontSize(10)
      .font('Helvetica')
      .moveDown()
      .text(`Status: ${String(inv.status || '').toUpperCase()}`);

    if (inv.dueDate) {
      d.text(`Due date: ${inv.dueDate}`);
    }

    if (inv.notes) {
      d.moveDown().text(inv.notes);
    }

    d.moveDown(2).text('Generated by Billora.');

    d.end();
  });
}

/* =========================================================
   HEALTH
========================================================= */

app.get('/api/health', (req, res) => {
  res.json({
    ok: true,
    app: 'Billora',
    database: 'json-file'
  });
});

/* =========================================================
   AUTH
========================================================= */

app.post('/api/auth/register', async (req, res) => {
  try {
    const {
      name,
      email,
      password,
      businessName
    } = req.body || {};

    if (!name || !email || !password) {
      return res.status(400).json({
        message: 'Name, email and password are required.'
      });
    }

    if (String(password).length < 8) {
      return res.status(400).json({
        message: 'Password must be at least 8 characters.'
      });
    }

    const e = String(email).trim().toLowerCase();

    if (await db.getUserByEmail(e)) {
      return res.status(409).json({
        message: 'An account with that email already exists.'
      });
    }

    const u = {
      id: id('usr'),
      name: String(name).trim(),
      email: e,
      businessName: String(
        businessName || `${name}'s Business`
      ).trim(),
      password: await bcrypt.hash(password, 10),
      plan: 'free',
      phone: '',
      address: '',
      currency: 'NGN',
      createdAt: new Date().toISOString()
    };

    const createdUser = await db.createUser(u);

    res.status(201).json({
      token: token(createdUser),
      user: pub(createdUser)
    });
  } catch (err) {
    res.status(500).json({
      message: err.message
    });
  }
});

app.post('/api/auth/login', async (req, res) => {
  try {
    const u = await db.getUserByEmail(
      String(req.body.email || '')
        .trim()
        .toLowerCase()
    );

    if (
      !u ||
      !(await bcrypt.compare(
        req.body.password || '',
        u.password
      ))
    ) {
      return res.status(401).json({
        message: 'Invalid email or password.'
      });
    }

    res.json({
      token: token(u),
      user: pub(u)
    });
  } catch (err) {
    res.status(500).json({
      message: err.message
    });
  }
});

app.get('/api/me', auth, async (req, res) => {
  const u = await db.getUser(req.user.id);

  if (!u) {
    return res.status(404).json({
      message: 'User not found.'
    });
  }

  res.json(pub(u));
});

/* =========================================================
   DASHBOARD / ANALYTICS
========================================================= */

app.get('/api/dashboard', auth, async (req, res) => {
  res.json(await db.dashboard(req.user.id));
});

app.get('/api/analytics', auth, async (req, res) => {
  res.json(await db.analytics(req.user.id));
});

/* =========================================================
   INVOICES
========================================================= */

app.get('/api/invoices', auth, async (req, res) => {
  res.json(await db.list('invoices', req.user.id));
});

app.post('/api/invoices', auth, async (req, res) => {
  try {
    const {
      customerName,
      customerEmail,
      items,
      dueDate,
      notes,
      vatRate
    } = req.body || {};

    if (
      !customerName ||
      !Array.isArray(items) ||
      !items.length
    ) {
      return res.status(400).json({
        message: 'Customer and at least one item are required.'
      });
    }

    const clean = items.map((item) => ({
      description: String(
        item.description || 'Item'
      ).trim(),
      quantity: Math.max(
        1,
        Number(item.quantity) || 1
      ),
      price: Math.max(
        0,
        Number(item.price) || 0
      )
    }));

    if (
      clean.some(
        (item) =>
          !item.description ||
          item.price <= 0
      )
    ) {
      return res.status(400).json({
        message:
          'Each item needs a description and price.'
      });
    }

    const subtotal = clean.reduce(
      (sum, item) =>
        sum + item.quantity * item.price,
      0
    );

    const rate = Math.max(
      0,
      Math.min(
        100,
        Number(vatRate) || 0
      )
    );

    const invoice = {
      id: id('inv'),
      userId: req.user.id,
      number: `INV-${String(Date.now()).slice(-8)}`,
      customerName: String(customerName).trim(),
      customerEmail: String(customerEmail || '').trim(),
      items: clean,
      subtotal,
      total: subtotal * (1 + rate / 100),
      status: 'unpaid',
      dueDate: dueDate || '',
      notes: String(notes || ''),
      vatRate: rate,
      createdAt: new Date().toISOString()
    };

    res.status(201).json(
      await db.addInvoice(invoice)
    );
  } catch (err) {
    res.status(500).json({
      message: err.message
    });
  }
});

app.patch('/api/invoices/:id', auth, async (req, res) => {
  if (
    !['paid', 'unpaid', 'overdue'].includes(
      req.body.status
    )
  ) {
    return res.status(400).json({
      message: 'Invalid invoice status.'
    });
  }

  const invoice = await db.updateInvoice(
    req.params.id,
    req.user.id,
    req.body.status
  );

  if (!invoice) {
    return res.status(404).json({
      message: 'Invoice not found.'
    });
  }

  res.json(invoice);
});

app.get(
  '/api/invoices/:id/:type',
  auth,
  async (req, res) => {
    const invoices = await db.list(
      'invoices',
      req.user.id
    );

    const invoice = invoices.find(
      (item) => item.id === req.params.id
    );

    if (!invoice) {
      return res.status(404).end();
    }

    const user = await db.getUser(req.user.id);

    const buffer = await pdf(
      invoice,
      user,
      req.params.type === 'receipt'
    );

    res.set({
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="Billora-${invoice.number}-${req.params.type}.pdf"`
    });

    res.send(buffer);
  }
);

// Health check
app.get('/api/health', (req, res) => {
  res.status(200).json({
    ok: true,
    service: 'Billora API',
    timestamp: new Date().toISOString()
  });
});

/* =========================================================
   EXPENSES
========================================================= */

app.get('/api/expenses', auth, async (req, res) => {
  res.json(
    await db.list('expenses', req.user.id)
  );
});

app.post('/api/expenses', auth, async (req, res) => {
  const {
    title,
    amount,
    category
  } = req.body || {};

  if (!title || Number(amount) <= 0) {
    return res.status(400).json({
      message:
        'Expense title and a positive amount are required.'
    });
  }

  res.status(201).json(
    await db.addExpense({
      id: id('exp'),
      userId: req.user.id,
      title: String(title).trim(),
      amount: Number(amount),
      category: category || 'General',
      createdAt: new Date().toISOString()
    })
  );
});

/* =========================================================
   SETTINGS
========================================================= */

app.get('/api/settings', auth, async (req, res) => {
  res.json(
    pub(await db.getUser(req.user.id))
  );
});

app.patch('/api/settings', auth, async (req, res) => {
  const u = await db.getUser(req.user.id);

  if (!u) {
    return res.status(404).json({
      message: 'User not found.'
    });
  }

  Object.assign(u, {
    name: String(
      req.body.name || u.name
    ).trim(),

    businessName: String(
      req.body.businessName ||
        u.businessName
    ).trim(),

    phone: String(
      req.body.phone || ''
    ).trim(),

    address: String(
      req.body.address || ''
    ).trim(),

    currency: ['NGN', 'USD', 'GBP'].includes(
      req.body.currency
    )
      ? req.body.currency
      : 'NGN'
  });

  res.json(
    pub(await db.updateUser(u))
  );
});

/* =========================================================
   TEAM
========================================================= */

app.get('/api/team', auth, async (req, res) => {
  res.json(
    await db.list(
      'members',
      req.user.id
    )
  );
});

app.post('/api/team/invite', auth, async (req, res) => {
  const {
    email,
    role
  } = req.body || {};

  if (!email) {
    return res.status(400).json({
      message: 'Team member email is required.'
    });
  }

  const member = {
    id: id('mem'),
    userId: req.user.id,
    email: String(email)
      .trim()
      .toLowerCase(),
    role:
      role === 'manager'
        ? 'manager'
        : 'staff',
    status: 'invited',
    token: crypto
      .randomBytes(24)
      .toString('hex'),
    createdAt: new Date().toISOString()
  };

  await db.addMember(member);

  const link =
    `${APP_URL}/?team_invite=${member.token}`;

  res.json({
    member: {
      email: member.email,
      role: member.role,
      status: member.status
    },
    sent: false,
    inviteLink: link,
    message:
      'Share this invitation link with the team member.'
  });
});

/* =========================================================
   RECURRING INVOICES
========================================================= */

app.get('/api/recurring', auth, async (req, res) => {
  res.json(
    await db.getRecurring(req.user.id)
  );
});

app.post('/api/recurring', auth, async (req, res) => {
  const {
    customerName,
    customerEmail,
    items,
    frequency,
    nextDate
  } = req.body || {};

  if (
    !customerName ||
    !Array.isArray(items) ||
    !items.length ||
    !nextDate
  ) {
    return res.status(400).json({
      message:
        'Customer, items and next date are required.'
    });
  }

  if (
    !['weekly', 'monthly', 'quarterly'].includes(
      frequency
    )
  ) {
    return res.status(400).json({
      message: 'Invalid frequency.'
    });
  }

  res.status(201).json(
    await db.addRecurring({
      id: id('rec'),
      userId: req.user.id,
      customerName,
      customerEmail: customerEmail || '',
      items,
      frequency,
      nextDate,
      status: 'active',
      createdAt: new Date().toISOString()
    })
  );
});

/* =========================================================
   REMINDERS
========================================================= */

app.post(
  '/api/reminders/email/:id',
  auth,
  async (req, res) => {
    res.status(503).json({
      message:
        'Email reminders are disabled because SMTP is not configured.'
    });
  }
);

app.get(
  '/api/reminders/whatsapp/:id',
  auth,
  async (req, res) => {
    const invoices = await db.list(
      'invoices',
      req.user.id
    );

    const invoice = invoices.find(
      (item) => item.id === req.params.id
    );

    if (!invoice) {
      return res.status(404).json({
        message: 'Invoice not found.'
      });
    }

    const user = await db.getUser(req.user.id);

    const message =
      `Hello ${invoice.customerName}, this is a friendly reminder from ${user.businessName} about invoice ${invoice.number} for ${Number(invoice.total).toLocaleString()} ${user.currency}.`;

    res.json({
      url: `https://wa.me/?text=${encodeURIComponent(
        message
      )}`
    });
  }
);

/* =========================================================
   FLUTTERWAVE PAYMENT
========================================================= */

app.post(
  '/api/payments/subscribe',
  auth,
  async (req, res) => {
    const secret =
      process.env.FLW_SECRET_KEY;

    if (!secret) {
      return res.status(503).json({
        message:
          'Flutterwave is not configured. Add FLW_SECRET_KEY on the server.'
      });
    }

    const user = await db.getUser(
      req.user.id
    );

    const tx_ref =
      `BILLORA-${user.id}-${Date.now()}`;

    try {
      const response = await fetch(
        'https://api.flutterwave.com/v3/payments',
        {
          method: 'POST',

          headers: {
            Authorization: `Bearer ${secret}`,
            'Content-Type': 'application/json'
          },

          body: JSON.stringify({
            tx_ref,
            amount: PRO_AMOUNT,
            currency: 'NGN',

            redirect_url:
              `${APP_URL}/?payment=complete&tx_ref=${encodeURIComponent(
                tx_ref
              )}`,

            payment_options:
              'card,banktransfer,ussd',

            customer: {
              email: user.email,
              name: user.name
            },

            customizations: {
              title: 'Billora Pro',
              description:
                'Billora monthly Pro subscription'
            }
          })
        }
      );

      const data =
        await response.json();

      if (
        !response.ok ||
        data.status !== 'success'
      ) {
        return res.status(502).json({
          message:
            data.message ||
            'Unable to start payment.'
        });
      }

      res.json({
        link: data.data.link,
        tx_ref
      });
    } catch (err) {
      res.status(502).json({
        message:
          'Flutterwave could not be reached.'
      });
    }
  }
);

/* =========================================================
   FLUTTERWAVE VERIFICATION
========================================================= */

app.get(
  '/api/payments/verify/:txRef',
  auth,
  async (req, res) => {
    const secret =
      process.env.FLW_SECRET_KEY;

    if (!secret) {
      return res.status(503).json({
        message:
          'Flutterwave is not configured.'
      });
    }

    try {
      const response = await fetch(
        `https://api.flutterwave.com/v3/transactions/verify_by_reference?tx_ref=${encodeURIComponent(
          req.params.txRef
        )}`,
        {
          headers: {
            Authorization:
              `Bearer ${secret}`
          }
        }
      );

      const data =
        await response.json();

      const user = await db.getUser(
        req.user.id
      );

      const verified =
        data.status === 'success' &&
        data.data?.status === 'successful' &&
        data.data?.tx_ref ===
          req.params.txRef &&
        data.data?.currency === 'NGN' &&
        Number(data.data?.amount) >=
          PRO_AMOUNT;

      if (verified) {
        user.plan = 'pro';
        await db.updateUser(user);
      }

      res.json({
        verified,
        user: pub(
          await db.getUser(
            req.user.id
          )
        )
      });
    } catch (err) {
      res.status(502).json({
        message:
          'Could not verify payment.'
      });
    }
  }
);

/* =========================================================
   FLUTTERWAVE WEBHOOK
========================================================= */

app.post(
  '/flw-webhook',
  async (req, res) => {
    const signature =
      req.headers['flutterwave-signature'] ||
      req.headers['verif-hash'];

    const secret =
      process.env.FLW_SECRET_HASH;

    if (!secret || !signature) {
      return res.status(401).end();
    }

    let valid =
      String(signature) ===
      String(secret);

    if (
      req.headers['flutterwave-signature']
    ) {
      valid =
        crypto
          .createHmac(
            'sha256',
            secret
          )
          .update(
            req.rawBody || ''
          )
          .digest('base64') ===
        signature;
    }

    if (!valid) {
      return res.status(401).end();
    }

    const payload =
      req.body || {};

    const eventId = String(
      payload.webhook_id ||
        payload.id ||
        payload.data?.id ||
        crypto
          .createHash('sha256')
          .update(
            req.rawBody ||
              JSON.stringify(payload)
          )
          .digest('hex')
    );

    if (
      !(await db.addPaymentEvent(
        eventId,
        payload
      ))
    ) {
      return res.sendStatus(200);
    }

    const data =
      payload.data || {};

    if (
      (
        payload.type ===
          'charge.completed' ||
        payload.event ===
          'charge.completed'
      ) &&
      ['successful', 'succeeded'].includes(
        data.status
      ) &&
      data.currency === 'NGN'
    ) {
      const tx =
        data.tx_ref ||
        data.reference ||
        '';

      const match =
        String(tx).match(
          /^BILLORA-(.+)-\d+$/
        );

      if (match) {
        const user =
          await db.getUser(
            match[1]
          );

        if (
          user &&
          Number(data.amount) >=
            PRO_AMOUNT
        ) {
          user.plan = 'pro';
          await db.updateUser(
            user
          );
        }
      }
    }

    res.sendStatus(200);
  }
);

/* =========================================================
   FRONTEND
========================================================= */

app.get('*', (req, res) => {
  res.sendFile(
    path.join(
      __dirname,
      'public',
      'index.html'
    )
  );
});

/* =========================================================
   DATABASE INITIALIZATION
========================================================= */

(async () => {
  try {
    await db.initDb();
  } catch (err) {
    console.error(
      'Database initialization failed:',
      err
    );
  }
})();

/* =========================================================
   VERCEL EXPORT
========================================================= */

module.exports = app;

/* =========================================================
   LOCAL DEVELOPMENT
========================================================= */

if (require.main === module) {
  app.listen(PORT, () => {
    console.log(
      `Billora running on port ${PORT}`
    );
  });
}
